[env:m5stack-tab5]
extends = esp32p4_base
board = m5stack-tab5-M005-V11
monitor_filters = esp32_exception_decoder
build_src_filter = 
  ${esp32p4_base.build_src_filter}
build_flags = 
  ${esp32p4_base.build_flags}
  -I variants/esp32p4/m5stack_tab5
lib_deps = 
  ${esp32p4_base.lib_deps}
